spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/library
      username: root
      password: liujianyu
mybatis:
  mapper-locations: classpath:mappers/*.xml
